### ISSUE TITLE
Dyslexia & Night modes in Angular Material button

### ISSUE THREAD

**Issue by danieldanielecki** [OswaldLabsOpenSource/agastya#116]
## Minimal Working Example

```
<a mat-button>My Text</a>
<mat-nav-list role="navigation">
  <a mat-list-item>Second Text</a>
</mat-nav-list>
```

## Expected Behaviour

Work as expected, i.e. apply certain CSS styles to these items (mat-button, mat-list-item [which is also mat-button], and display correctly as other elements.

## Current Behaviour

Using button of Angular Material there's just a rectangle of certain colour, without distinguishing that there's a text inside. The easiest how does it works is to check the screenshots below (the same behaviour is with Night mode). On the pictures sidebar is used as a mobile menu, whilst toolbar as a menu for desktop.

![sidebar](https://user-images.githubusercontent.com/12736263/54919469-2ec90b80-4f01-11e9-8e09-4cef7a38240d.PNG)
![toolbar](https://user-images.githubusercontent.com/12736263/54919471-2ec90b80-4f01-11e9-8260-d0fc20c27805.PNG)

**Comment by AnandChowdhary** [comment]
Hi @danieldanielecki, thanks for opening an issue! We're going to release Agastya v4 in the next week (at most, two weeks) and most of these issues should already be fixed. If not, I'll personally have a look.

In the meantime, you can manually change the URL of your loader from `agastya-loader.oswaldlabs.com` to `staging-agastya-loader.oswaldlabs.com` to see it in action!

If you need any specific help with a feature, you can also write to yourfriends@oswaldlabs.com.

**Comment by danieldanielecki** [comment]
Hi @AnandChowdhary, checked the 4.0.0 version on different project and the problems remains the same, please take a look into the screenshots. It seems to be there's a problem with when it's supposed to work together with [Angular Material's components](https://material.angular.io/components/categories). So far noticed the issue on the following elements: mat-button, mat-card, mat-list-item, mat-table.

Link for the project with v4: [https://klm-test-dev.web.app/](https://klm-test-dev.web.app/)

Screenshots
![agastya_normal](https://user-images.githubusercontent.com/12736263/58464562-3477e300-8136-11e9-9067-800c3636d8ba.PNG)
![agastya_dyslexia](https://user-images.githubusercontent.com/12736263/58464574-393c9700-8136-11e9-9c7b-c9c4b1cb62dd.PNG)
![agastya_night](https://user-images.githubusercontent.com/12736263/58464583-3a6dc400-8136-11e9-8370-4b7a50575df6.PNG)

**Comment by AnandChowdhary** [comment]
Looks like you're still on v3. Can you try the script tag here (the NPM package is not on v4 yet)?

https://help.oswaldlabs.com/developers/installation.html

**Comment by AnandChowdhary** [comment]
This has been fixed in Agastya 4.1. 😄
